spring:
  data:
    mongodb:
      uri: mongodb+srv://chatgpt:riten13@cluster0.ioo4yf3.mongodb.net/food_database?appName=Cluster0

server:
  port: 3000

logging:
  level:
    com.example.fooddatabase: DEBUG
