package com.example.fooddatabase.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO used when returning a food to the client (response body).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Food details returned by the API")
public class FoodResponse {

    @Schema(description = "Unique ID of the food (generated by MongoDB)", example = "66f1a2b3c4d5e6f7a8b9c0d1")
    private String id;

    @Schema(description = "Name of the food", example = "Chicken Breast")
    private String name;

    @Schema(description = "Category of the food", example = "Meat")
    private String category;

    @Schema(description = "Short description of the food", example = "Skinless boneless chicken breast")
    private String description;

    @Schema(description = "Embedded nutrition information for this food")
    private NutritionDto nutrition;
}
