spring:
  application:
    name: grocery-planning-service

  data:
    mongodb:
      uri: 
      database: grocery_planning_db

server:
  port: 3002

food-service:
  url: http://localhost:3000

meal-planning-service:
  url: http://localhost:3001

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
